[phases.setup]
nixPkgs = ["python39", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python app.py"
